import os

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID")

EMA_FAST = 8
EMA_MID  = 21
EMA_SLOW = 50

RSI_LEN = 14
RSI_OB  = 70
RSI_OS  = 30

MACD_FAST = 12
MACD_SLOW = 26
MACD_SIG  = 9

ATR_LEN      = 14
ATR_SL_MULT  = 1.2
ATR_TP1_MULT = 1.5
ATR_TP2_MULT = 2.5
